environment:
  MYGET_KEY:
    secure: 3HSNmGS95yv4VGx8Mi2S+6xdKZ1Qkvr0P3tGYWYJu235GUGWUyXbHx1iZ4gmqeP2

branches:
  except:
  - demo
  - gh-pages

skip_tags: true

version: 1.1.{build}

build_script:
  - ps: .\build.ps1
